name: CI master

on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - '.github/**'
    #   - '.vscode/**'
    #   - 'bin/**'
    #   - '.gitignore'
    #   - '.dockerignore'
    #   - '*.md'

permissions:
  id-token: write
  contents: write

concurrency:
  group: ci-master
  cancel-in-progress: true

env:
  GITHUB_HEAD_SHA: ${{ github.sha }}

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get datetime tag
        id: vars
        run: echo "TAG=$(git log -1 --format=%cd --date=format:'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      - name: Bump version and push tag
        uses: jasonamyers/github-bumpversion-action@v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ steps.vars.outputs.TAG }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: false

  build:
    uses: ./.github/workflows/shared-build.yaml
    needs:
      - bump
    with:
      gh-release: true

  tigger-deployment:
    needs:
      - bump
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        env:
          tag: "${{ needs.bump.outputs.tag }}"
        run: |
          echo "${{ env.tag }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_WORKFLOW_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/appgrid-online/appgrid-iac/dispatches \
            -d '{"event_type":"deploy_snappass","client_payload":{"version":"${{ env.tag }}"}}'
